# *** Base Yazi ***
# Forcefully exit Yazi by opening a shell at the current location
[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = "J"
run = "arrow 5"
desc = "Move cursor down 5"

[[mgr.prepend_keymap]]
on = "K"
run = "arrow -5"
desc = "Move cursor up 5"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"
desc = "Jump to a directory via zoxide"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"

# Disable the default keybinding g => d for going to ~/Downloads
[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "noop"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = "cd /"
desc = "Go /"

[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/college/WSU/'2026 Spring Semester'"
desc = "Go WSU"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/storage/sda1recrypt/6042"
desc = "Go 6042"

# *** Plugins ***
# toggle-pane (https://github.com/yazi-rs/plugins/tree/main/toggle-pane.yazi)
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# zoom (https://github.com/yazi-rs/plugins/tree/main/zoom.yazi)
[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"
