# *** Base Yazi ***
[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = "J"
run = "arrow 5"
desc = "Move cursor down 5"

[[mgr.prepend_keymap]]
on = "K"
run = "arrow -5"
desc = "Move cursor up 5"

[[mgr.prepend_keymap]]
on = "r"
run = ["rename --cursor=start", "input:escape"]
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"
desc = "Jump to a directory via zoxide"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = "cd /"
desc = "Go /"

[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/college/WSU/'2026 Spring Semester'"
desc = "Go WSU"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/storage/sda1/6042"
desc = "Go 6042"

# *** Plugins ***
# toggle-pane (https://github.com/yazi-rs/plugins/tree/main/toggle-pane.yazi)
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# zoom (https://github.com/yazi-rs/plugins/tree/main/zoom.yazi)
[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"
