[display]
compact = true

[style.description]
# gray
foreground = { rgb = { r = 202, g = 202, b = 206 } }

[style.command_name]
# orange
foreground = { rgb = { r = 255, g = 138, b = 92 } }

[style.example_text]
# red
foreground = { rgb = { r = 255, g = 102, b = 133 } }

[style.example_code]
# blue
foreground = { rgb = { r = 102, g = 178, b = 240 } }

[style.example_variable]
# green
foreground = { rgb = { r = 31, g = 204, b = 0 } }
underline = true

[updates]
auto_update = true
# refresh cache every 14 days/2 weeks
auto_update_interval_hours = 336
